/*
 * generated by Xtext 2.15.0
 */
package net.eldm.core


/**
 * Use this class to register components to be used at runtime / without the Equinox extension registry.
 */
class SchDslRuntimeModule extends AbstractSchDslRuntimeModule {
}
