/*
 * generated by Xtext 2.15.0
 */
package net.eldm.core


/**
 * Initialization support for running Xtext languages without Equinox extension registry.
 */
class SchDslStandaloneSetup extends SchDslStandaloneSetupGenerated {

	def static void doSetup() {
		new SchDslStandaloneSetup().createInjectorAndDoEMFRegistration()
	}
}
