/*
 * generated by Xtext 2.15.0
 */
package net.eldm.tests

import com.google.inject.Inject
import net.eldm.schDsl.Model
import org.eclipse.xtext.testing.InjectWith
import org.eclipse.xtext.testing.extensions.InjectionExtension
import org.eclipse.xtext.testing.util.ParseHelper
import org.junit.jupiter.api.Test
import org.junit.jupiter.api.^extension.ExtendWith

import static extension net.eldm.tests.TestHelper.*

@ExtendWith(InjectionExtension)
@InjectWith(SchDslInjectorProvider)
class SchDslParsingTest {
  @Inject ParseHelper<Model> ph

  @Test
  def void testModel() {
    ph.test('''
      datatype String
       
      entity Blog {
          title: String
          many posts: Post
      }
       
      entity HasAuthor {
          author: String
      }
       
      entity Post extends HasAuthor {
          title: String
          content: String
          many comments: Comment
      }
       
      entity Comment extends HasAuthor {
          content: String
      }
    ''')
  }
}
