/*
 * generated by Xtext 2.15.0
 */
package net.eldm.scoping;

import org.eclipse.xtext.scoping.impl.DelegatingScopeProvider;

public abstract class AbstractEldmDslScopeProvider extends DelegatingScopeProvider {
}
