/*
 * generated by Xtext 2.15.0
 */
package net.eldm.parser.antlr;

import com.google.inject.Inject;
import net.eldm.parser.antlr.internal.InternalEldmDslParser;
import net.eldm.services.EldmDslGrammarAccess;
import org.antlr.runtime.CharStream;
import org.antlr.runtime.TokenSource;
import org.eclipse.xtext.parser.antlr.AbstractAntlrParser;
import org.eclipse.xtext.parser.antlr.XtextTokenStream;

public class EldmDslParser extends AbstractAntlrParser {

	@Inject
	private EldmDslGrammarAccess grammarAccess;

	@Override
	protected void setInitialHiddenTokens(XtextTokenStream tokenStream) {
		tokenStream.setInitialHiddenTokens("RULE_WS", "RULE_ML_COMMENT", "RULE_SL_COMMENT");
	}
	
	@Override
	protected TokenSource createLexer(CharStream stream) {
		return new EldmDslTokenSource(super.createLexer(stream));
	}
	
	/**
	 * Indentation aware languages do not support partial parsing since the lexer is inherently stateful.
	 * Override and return {@code true} if your terminal splitting is stateless.
	 */
	@Override
	protected boolean isReparseSupported() {
		return false;
	}

	@Override
	protected InternalEldmDslParser createParser(XtextTokenStream stream) {
		return new InternalEldmDslParser(stream, getGrammarAccess());
	}

	@Override 
	protected String getDefaultRuleName() {
		return "Module";
	}

	public EldmDslGrammarAccess getGrammarAccess() {
		return this.grammarAccess;
	}

	public void setGrammarAccess(EldmDslGrammarAccess grammarAccess) {
		this.grammarAccess = grammarAccess;
	}
}
