/*
 * generated by Xtext 2.15.0
 */
package net.eldm.ide

import com.google.inject.Guice
import net.eldm.core.SchDslRuntimeModule
import net.eldm.core.SchDslStandaloneSetup
import org.eclipse.xtext.util.Modules2

/**
 * Initialization support for running Xtext languages as language servers.
 */
class SchDslIdeSetup extends SchDslStandaloneSetup {

	override createInjector() {
		Guice.createInjector(Modules2.mixin(new SchDslRuntimeModule, new SchDslIdeModule))
	}
	
}
