/*
 * generated by Xtext 2.15.0
 */
package net.eldm


/**
 * Initialization support for running Xtext languages without Equinox extension registry.
 */
class EldmDslStandaloneSetup extends EldmDslStandaloneSetupGenerated {

	def static void doSetup() {
		new EldmDslStandaloneSetup().createInjectorAndDoEMFRegistration()
	}
}
