/*
 * generated by Xtext 2.15.0
 */
package net.eldm.parser.antlr;

import net.eldm.parser.antlr.internal.InternalEldmDslParser;
import org.antlr.runtime.Token;
import org.antlr.runtime.TokenSource;
import org.eclipse.xtext.parser.antlr.AbstractIndentationTokenSource;

public class EldmDslTokenSource extends AbstractIndentationTokenSource {

	public EldmDslTokenSource(TokenSource delegate) {
		super(delegate);
	}

	@Override
	protected boolean shouldSplitTokenImpl(Token token) {
		// TODO Review assumption
		return token.getType() == InternalEldmDslParser.RULE_WS;
	}

	@Override
	protected int getBeginTokenType() {
		// TODO Review assumption
		return InternalEldmDslParser.RULE_BEGIN;
	}

	@Override
	protected int getEndTokenType() {
		// TODO Review assumption
		return InternalEldmDslParser.RULE_END;
	}

}
