/*
 * generated by Xtext 2.15.0
 */
package net.eldm.ui;

import com.google.inject.Injector;
import net.eldm.ui.internal.EldmActivator;
import org.eclipse.core.runtime.Platform;
import org.eclipse.xtext.ui.guice.AbstractGuiceAwareExecutableExtensionFactory;
import org.osgi.framework.Bundle;

/**
 * This class was generated. Customizations should only happen in a newly
 * introduced subclass. 
 */
public class EldmDslExecutableExtensionFactory extends AbstractGuiceAwareExecutableExtensionFactory {

	@Override
	protected Bundle getBundle() {
		return Platform.getBundle(EldmActivator.PLUGIN_ID);
	}
	
	@Override
	protected Injector getInjector() {
		EldmActivator activator = EldmActivator.getInstance();
		return activator != null ? activator.getInjector(EldmActivator.NET_ELDM_ELDMDSL) : null;
	}

}
